services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
  postgres:
    image: postgres:14.11-alpine3.19
    environment:
      POSTGRES_USER: listing
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./src/main/resources/scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
